### ISSUE TITLE
Issue unpacking OFP 

### ISSUE THREAD

**Issue by zedug** [italorecife/OppoRealme-OFP-Flash#20]
Hi
tyring to flash RMX2001 with stock firmware on win11 but I get the error msg below in both the windows x64 and the python versions :

```
Searching for .ofp files
File found: RMX2001export_11_C.18_2022031723520000.ofp
Traceback (most recent call last):
  File "C:\Users\laure\AppData\Local\Temp\ONEFIL~1\flash.py", line 515, in <module>
  File "C:\Users\laure\AppData\Local\Temp\ONEFIL~1\flash.py", line 316, in main
  File "C:\Users\laure\AppData\Local\Temp\ONEFIL~1\flash.py", line 109, in generatekey
  File "C:\Users\laure\AppData\Local\Temp\ONEFIL~1\flash.py", line 127, in extract_xml
struct.error: unpack requires a buffer of 4 bytes
```

Any hint to debug this ?
tia

**Comment by ambroziewiczdaniel** [comment]
I have the same error when trying to flash Realme 8i.

**Comment by babai93** [comment]
I am also getting same issue.
```
OppoRealme-OFP-Flash_1.0.exe
Oppo/Realme Flash .OFP File on Bootloader | 1.0 (c) 2022 | Italo Almeida (@SirCDA) - GPL-3.0 License

Usage: Put the .ofp file in the same folder as the program,
then put your device in mode fastboot to start flash.

Note: if your device was not recognized in fastboot
mode by the computer, try to install the adb drivers.
=======================

Searching for .ofp files
File found: RMX2117export_11_C.12_2022041914110169.ofp
Traceback (most recent call last):
  File "C:\Users\babai\AppData\Local\Temp\ONEFIL~1\flash.py", line 515, in <module>
  File "C:\Users\babai\AppData\Local\Temp\ONEFIL~1\flash.py", line 316, in main
  File "C:\Users\babai\AppData\Local\Temp\ONEFIL~1\flash.py", line 109, in generatekey
  File "C:\Users\babai\AppData\Local\Temp\ONEFIL~1\flash.py", line 127, in extract_xml
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by rexsllemel** [comment]
Did you managed to solve this? I am also facing this problem using RM2001

**Comment by zedug** [comment]
Unfortunately no

Jul 27, 2023 03:46:34 xPiLoYx 
***@***.***>:

**Comment by rabe33h** [comment]
No solution for this??
How should i flash ofp then?
