### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by VaibhavNalawade** [italorecife/OppoRealme-OFP-Flash#23]
File found: RMX3241export_11_A.15_2022051311190273.ofp
Traceback (most recent call last):
  File "/home/vaibhav/OppoRealme-OFP-Flash/flash.py", line 515, in <module>
    main()
  File "/home/vaibhav/OppoRealme-OFP-Flash/flash.py", line 316, in main
    pagesize,key,iv,data=generatekey(ofpfile)
                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/vaibhav/OppoRealme-OFP-Flash/flash.py", line 109, in generatekey
    pagesize,data=extract_xml(filename,key,iv)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vaibhav/OppoRealme-OFP-Flash/flash.py", line 127, in extract_xml
    offset=unpack("<I",rf.read(4))[0]*pagesize
           ^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

**Comment by Muzammil011** [comment]
same
